# Generated by Django 5.2.6 on 2025-09-29 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_roomimage_image_alter_roomimage_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('cancelled', 'Cancelada')], default='pending', max_length=10),
        ),
    ]
